---
config:
  layout: elk
---
flowchart BT

subgraph Students["&lt;process&gt;"]
    Qwen["`***Ex. qwen3.5-9b***`"]
    Gemma["`***Ex. gemma4-12b***`"]
    OSS["`***Ex. gpt-oss-20b***`"]
end

subgraph Teachers["&lt;process&gt;"]
    claude["`***Ex. claude-sonnet-5***`"]
    gemini["`***Ex. gemini-3.5-pro***`"]
    openai["`***Ex. gpt-5.5***`"]
end

subgraph Actors["&lt;process&gt;"]
    logic(["`***Ex. gpt-oss-20b***`"])
    feelings(["`***Ex. gpt-oss-120b***`"])
    action(["`***Ex. gpt-5.5***`"])
end

%% Workflow Logic
Qwen@{ shape: terminal}
Gemma@{ shape: terminal}
OSS@{ shape: terminal}
student@{ shape: proc}
claude@{ shape: terminal}
gemini@{ shape: terminal}
openai@{ shape: terminal}
teacher@{ shape: proc}
actor@{ shape: proc}
verify@{ shape: decision}
plan@{ shape: procs}
execute@{ shape: event}
observation@{ shape: dbl-circ}
orchestrator@{ shape: procs}

%% Workflow Feelings
style Qwen fill:#DD7777,color:#fff
style Gemma fill:#7777DD,color:#fff
style OSS fill:#77DD77
style claude fill:#DD7777,color:#fff
style gemini fill:#7777DD,color:#fff
style openai fill:#77DD77
style logic fill:#DD7777,color:#fff
style feelings fill:#7777DD,color:#fff
style action fill:#77DD77
style observation fill:#77DD77,font-size:24px
style orchestrator fill:#77DD77,color:#000
style student fill:#DD7777,color:#fff,font-size:24px
style Students stroke:#DD7777
style teacher fill:#7777DD,color:#fff,font-size:24px
style Teachers stroke:#0000DD
style actor fill:#77DD77,font-size:24px
style verify fill:#77DD77
style plan fill:#77DD77
style Actors stroke:#77DD77,fill:#77DD77
style execute fill:#77DD77

%% Workflow Action
observation["`**Observer**`"] x--x orchestrator["<b>HERMES.md <br>tasks<br>STUDENT.md<br>then<br>TEACHER.md</b>"]
student["`***Student node***`"] --o observation
student --- Students
Qwen --> Gemma
Gemma --> OSS
Students --x teacher["`***Teacher node***`"]
teacher --- Teachers
claude --> gemini
gemini --> openai
Teachers --- observation
actor["`***Execution node***`"] --- observation
actor --x verify["`***Verify and nurture?***`"]
plan["`***Action plan secured***`"] --- verify & Actors
Actors --- execute["`***Action execute!***`"]
logic --> feelings
feelings --> action
execute --> observation